services:
  data-retriever:
    build:
      context: ./data-retriever  # Specify the Dockerfile location
    container_name: data-retriever
    volumes:
      - ./data-retriever/data:/data-retriever/data # Map the local data folder
      - ./data-retriever/log:/data-retriever/logs
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1

