name: HorizonHacks2024 
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - flask-sqlalchemy
  - flask=3.0
  - flask-session
  - pandas==2.1.4
  - pymysql
  - sqlalchemy=1.4.*
  - matplotlib
  - python=3.10.*
  - python-dotenv
  - tensorflow=2.14.0

